name: ⚔️ Quest Submission (Unstake Request)
description: ส่งงานเพื่อผ่านด่านและขอรับเงิน Stake คืน
title: "[QUEST] ส่งงาน: <ชื่อ Quest> โดย @<GithubUsername>"
labels: ["quest-submission", "needs-review"]
body:
  - type: input
    id: discord_id
    attributes:
      label: Discord Username
      description: Discord Username เพื่อปรับ Rank
      placeholder: example#1234
    validations:
      required: true

  - type: input
    id: tx_hash
    attributes:
      label: Staking Transaction Hash
      description: หลักฐานการโอนเงิน Stake (Tx Hash)
      placeholder: 5P3GiW...
    validations:
      required: true

  - type: input
    id: public_key
    attributes:
      label: Your Public Key (Wallet Address)
      description: ที่อยู่ Wallet ที่คุณใช้ Stake และต้องการรับเงินคืน
      placeholder: 4zMM9G...
    validations:
      required: true

  - type: input
    id: repo_link
    attributes:
      label: Repository / PR Link
      description: ลิงก์ของงานที่ทำเสร็จแล้ว
    validations:
      required: true

  - type: textarea
    id: learnings
    attributes:
      label: What did you learn?
      description: สรุปสั้นๆ ว่าได้เรียนรู้อะไรจาก Quest นี้
    validations:
      required: true
